name: Pylint and Pytest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pytest requests

    - name: Analyze code with pylint
      run: |
        pylint Ipadd.py app.py

    - name: Run tests with pytest
      run: |
        pytest

    - name: Run the Python script
      run: |
        python Ipadd.py
        python app.py
